### ISSUE TITLE
docker-compose ps in blog article

### ISSUE THREAD

**Issue by timmaybrown** [autopilotpattern/nodejs-example#13]
Thank you for this example and the blog post here ( https://www.joyent.com/blog/microservices-containers-nodejs )

Didn't see how to comment on the blog, but thought I'd mention one thing that hung me up at first with running the `docker-compose ps` command to check on the status of the local containers. It kept saying it couldn't find the `_env` file because it was defaulting to using the `docker-compose.yml` file.

The command needs to be `docker-compose -f local-compose.yml ps` 

Thanks again for sharing this and excited to try and apply the autopilotpattern to my applications.

**Comment by geek** [comment]
@timmaybrown good point, interested in creating a pull request to update the readme?

**Comment by timmaybrown** [comment]
Sure thing.

**Comment by timmaybrown** [comment]
Closed from pull #14 . :+1:
