### ISSUE TITLE
setup problem

### ISSUE THREAD

**Issue by Matrixbirds** [autopilotpattern/nodejs-example#23]
When i was run this command
```bash
docker-compose -f docker-compose.yml up
```
I got this messages as below
```bash
ERROR: Couldn't find env file _env
```

I think maybe u exclude _env file

**Comment by geek** [comment]
@Matrixbirds please use `docker-compose -f local-compose.yml up` for running the example locally. When you are ready to try the example on [triton](https://www.joyent.com/triton/compute) run `setup.sh` to generate the `_env` file, then use `docker-compose up` or `triton-compose up` [triton-compose](https://github.com/joyent/triton-docker-cli)

**Comment by Matrixbirds** [comment]
thx
