### ISSUE TITLE
localhost:10001 not found

### ISSUE THREAD

**Issue by nianqing99** [autopilotpattern/nodejs-example#24]
hello, when i download the example code ,and i want to start this example.but i got a error that i can't seen 3 charts in the browser.
![image](https://user-images.githubusercontent.com/10056390/28532816-8a3aa226-70cd-11e7-8a5b-02979b889533.png)

but i have build the project already.
![image](https://user-images.githubusercontent.com/10056390/28532833-99a2e9f8-70cd-11e7-9626-dd077e9f2ff6.png)
can you give me some advices?

**Comment by geek** [comment]
@qweqweq port 10001 won't be published externally by default. Instead, we are using traefik to route traffic to the frontend. Use port 80, which will balance to any frontend instances you have. `http://localhost` This means that you can `docker-compose -f local-compose.yml scale frontend=3`

**Comment by nianqing99** [comment]
@geek  thank you 👍

**Comment by leoj3n** [comment]
@geek Should the `README.md` reflect this information?

**Comment by geek** [comment]
@leoj3n yes, it looks like the readme should be updated. If you want to submit a PR that will be appreciated, otherwise I'll update this week.

Thanks!

**Comment by leoj3n** [comment]
@geek Please see #29
